apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
commonAnnotations:
  sample-version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: thakurashish55525/sample-app-springboot:20
        resources:
          requests:
            memory: "80Mi"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: springboot-app
            mountPath: /etc/springboot
      volumes:
      - name: conf
        emptyDir: {}
      - name: springboot-app
        configMap:
          name: springboot-app-cm
