apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  annotations: 
    sample-version: v3
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-boot-app

# commonAnnotations:
#   sample-version: v3
