apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE football;
    CREATE TABLE `squad` (
        `name` varchar(15) PRIMARY KEY NOT NULL
    );
    USE football;
    ...