apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: thakurashish55525/mysql:latest
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "200Mi"    # Minimum memory requested
              cpu: "200m"        # Minimum CPU requested
            limits:
              memory: "300Mi"    # Maximum memory allowed
              cpu: "500m"           # Maximum CPU allowed
          volumeMounts:
            - name: mysql-store
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: MYSQL_ROOT_PASSWORD
      volumes:
      - name: conf
        emptyDir: {}
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
  volumeClaimTemplates:
    - metadata:
        name: mysql-store
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 6Gi