apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: operators
spec:
  project: default
  source:
    repoURL: https://github.com/ashishthakur55525/springboot-app.git
    targetRevision: HEAD
    path: mysql-manifests
  destination: 
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true