apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: operators
spec:
  project: default
  source:
    repoURL: https://github.com/ashishthakur55525/springboot-app.git
    targetRevision: HEAD
    path: mysql-manifests/memsql
  destination: 
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: operators
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
